spring.application.name=backoffice

# Configuration de base de donnees - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/visa
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA pour PostgreSQL (correction du dialecte)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Frontend configuration
frontend.url=http://localhost:5173
frontend.suivi.path=/suivi

# Logging
logging.level.org.springframework.test=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Context  
server.servlet.context-path=/visa